### ISSUE TITLE
xinitrc is not discovered on new installations 

### ISSUE THREAD

**Issue by Narekmarg** [k4z4n0v4/Rayis#1]
First of all, I would like to thank the author for these brilliant configs. 
_Beatiful terminals. Magnificent shadows. Rounded corners. Pure heaven._  

During the recent deployments of these configurations on various machines we learned that xinit fails to discover the xinitrc file located in the ~/.config/X11 folder. 

For this to work we need an env variable to be set in .bashrc or in the equivalent file for other shells. 

Thanks

**Comment by k4z4n0v4** [comment]
issue is resolved in latest commit, please review

**Comment by Narekmarg** [comment]
Thanks a lot!!!
